pub const KLPT_RANDOM_PRIME_ATTEMPTS: u32 = 64;
pub const KLPT_REPRES_NUM_GAMMA_TRIAL: u32 = 32768;
pub const KLPT_GAMMA_EXPONENT_CENTER_SHIFT: u32 = 15;
pub const KLPT_KEYGEN_NUM_GAMMA_TRIAL: u32 = 64;
pub const KLPT_GAMMA_EXPONENT_INTERVAL_SIZE: u32 = 0;
pub const KLPT_KEYGEN_LENGTH: u32 = 1305;
pub const KLPT_SIGNING_NUMBER_STRONG_APPROX: u32 = 6784;
